columns:
  applicant_id:
    required: true
    aliases:
      - NO KP
      - no kp
      - no_kp
      - applicant_id
      - applicant id
  applicant_name:
    required: false
    aliases:
      - NAMA
      - nama
      - applicant_name
      - applicant name
  marital_status:
    required: false
    aliases:
      - MARITAL_STATUS
      - marital_status
      - marital status
  spouse_name:
    required: false
    aliases:
      - Nama Pasangan
      - spouse_name
      - spouse name
  spouse_id:
    required: false
    aliases:
      - NoKPPasangan
      - spouse_id
      - spouse id
  postgraduate_status:
    required: false
    aliases:
      - POSTGRADUATE_PAPER_STATUS
      - postgraduate_status
      - postgraduate paper status
  personal_health_condition:
    required: false
    aliases:
      - PERSONAL_HEALTH_CONDITION
      - personal_health_condition
      - personal health condition
  personal_health_details:
    required: false
    aliases:
      - Keterangan Kesihatan
      - keterangan kesihatan
      - personal_health_details
      - personal health details
  applicant_oku_status:
    required: false
    aliases:
      - StatusOKU
      - status_oku
      - oku_status
      - applicant_oku_status
  spouse_employment_status:
    required: false
    aliases:
      - SPOUSE_EMPLOYMENT_STATUS
      - spouse_employment_status
      - spouse employment status
  spouse_job_title:
    required: false
    aliases:
      - Pekerjaan Pasangan
      - pekerjaan pasangan
      - spouse_job_title
      - spouse job title
  spouse_work_address:
    required: false
    aliases:
      - Alamat Bekerja Pasangan
      - alamat bekerja pasangan
      - spouse_work_address
      - spouse work address
  spouse_work_state:
    required: false
    aliases:
      - NegeriBekerjaPasangan
      - negeri bekerjapasangan
      - spouse_work_state
      - spouse work state
  spouse_oku_status:
    required: false
    aliases:
      - SPOUSE_STATUS_OKU
      - spouse_status_oku
      - spouse_oku_status
      - spouse oku status
  spouse_health_condition:
    required: false
    aliases:
      - SPOUSE_HEALTH_CONDITION
      - spouse_health_condition
      - spouse health condition
  spouse_health_details:
    required: false
    aliases:
      - Keterangan Masalah Kesihatan Pasanga
      - keterangan masalah kesihatan pasanga
      - spouse_health_details
      - spouse health details
  email:
    required: false
    aliases:
      - EMAIL
      - EMEL
      - email
  gender:
    required: false
    aliases:
      - GENDER
      - gender
  current_headquarters:
    required: false
    aliases:
      - CURRENT_HEADQUARTERS
      - current_headquarters
  current_placement:
    required: false
    aliases:
      - PENEMPATAN TERKINI
      - 'PENEMPATAN TERKINI '
      - current_placement
  pdf_filename:
    required: false
    aliases:
      - Sheet1.NamaFail
      - NamaFail
      - pdf_filename
      - pdf file name
  pdf_url:
    required: false
    aliases:
      - Sheet1.DownloadURL
      - DownloadURL
      - pdf_url
      - download_url
